title: About Me'
author: Justin Ham
email: jham@ebnet.org
description: > # this means to ignore newlines until "baseurl:"
  Stuff about Me

# social links
instagram_username: just_in_a_ham
github_username:  just8ham

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
